site_name: STLP-Resources
site_url: https://pchs-projectprogramming.github.io/KySTLPEngineers23/
site_author: "Mason A. Thompson & My Fellow STLP Engineers"
copyright: Copyright &copy; 2022-2023 Mason A. Thompson & All Other Contributing Parties

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: slate
  font: 
    text: Gulzar
    code: Gulzar
  features:
    - navigation.sections
    - navigation.instant
  include_search_page: false
  search_index_only: true
  logo: assets/site-assets/favicon.png
  favicon: assets/site-assets/STLP-2019-favicon.png

extra:
  homepage: https://PCHS-ProjectProgramming.github.io/KySTLPEngineers23/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PCHS-ProjectProgramming
    - icon: fontawesome/solid/paper-plane
      link: mailto:mason.thompson@stu.pulaski.kyschools.us
    - icon: fontawesome/solid/school
      link: https://stlp.education.ky.gov/
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: True

nav:
  - Home: https://PCHS-ProjectProgramming.github.io/KySTLPEngineers23/
  - STLP Resources:
    - KY STLP Site: http://stlp.education.ky.gov
    - STLP Super Sheet: https://docs.google.com/spreadsheets/d/10nJTf0FhPypjOaoGnBgcFSYEr0wzyf-GtfidHUkod5Q/edit#gid=1709744959
    - STLP Project Toolkit: https://docs.google.com/presentation/d/1PsmAygFSIYVyDSC3zV8dVwBf8FgGvZnBsULznBTxhSA/edit#slide=id.ga47626b35a_1_80
    - Level Up! Badges: https://sites.google.com/education.ky.gov/stlplevelup/home
    - DPOJ Categories Slide Deck: https://docs.google.com/presentation/d/12mtb1hg7or6MW-Qnw-L08LC73bFKauade4b4LHi_cWI/edit#slide=id.gf9bd39e577_0_268
  - Extras:
    - Github: https://github.com/PCHS-ProjectProgramming/kystlpengineers23
    - Meet The Crew!: documentation/Meet-The-Crew.md
    - Contact Us: documentation/Contact-Us.md
